version: "3.9"
services:
  
  app:
    build: cmd
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=avitodev
      - DB_PASSWORD=pg4afl
      - DB_NAME=avito-flats
      - DB_PORT=5432
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data    
volumes:
  postgres_data:


postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "avito-flats"
      POSTGRES_USER: "avito-dev"
      POSTGRES_PASSWORD: "pg4afl"
    ports:
      - "5432:5432"