-- Создание таблицы flats
CREATE TABLE public.flats (
    id bigint generated by default as identity primary key not null,
    house_id integer NOT NULL,
    flat_number integer NOT NULL,
    rooms integer NOT NULL,
    price numeric(10,2) NOT NULL,
    user_id integer NOT NULL,
    moderation_status smallint NOT NULL,
    moderated_by string NOT NULL
    CONSTRAINT flats_pkey PRIMARY KEY (id),
    CONSTRAINT flats_moderation_status_check CHECK (moderation_status = ANY (ARRAY[0, 1])),
    CONSTRAINT flats_house_id_fkey FOREIGN KEY (house_id)
        REFERENCES public.houses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT flats_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- Создание таблицы houses
CREATE TABLE public.houses (
    id bigint generated by default as identity primary key not null,
    address character varying(255) NOT NULL,
    build_year integer NOT NULL,
    developer character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT houses_pkey PRIMARY KEY (id)
);

-- Триггер для обновления поля updated_at в таблице houses
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_houses_updated_at
BEFORE UPDATE ON public.houses
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Создание таблицы users
CREATE TABLE public.users (
    user_id string primary key not null,
    usertype smallint NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_role_check CHECK (usertype = ANY (ARRAY[0, 1]))
);